In [6]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline 
#modelling 
from  sklearn.metrics  import mean_squared_error,r2_score
from  sklearn.neighbors import KNeighborsRegressor
from  sklearn.tree import DecisionTreeRegressor
from  sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from  sklearn.svm import SVR
from sklearn.linear_model  import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost  import XGBRegressor
import warnings

<frozen importlib._bootstrap>:488: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 232 from PyObject

In [7]:
df = pd.read_csv('data/stud.csv')

In [8]:
df.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [9]:
X = df.drop(columns=['math_score'],axis=1)

In [10]:
X.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 7 columns]

In [11]:
y = df['math_score']

In [12]:
num_features = X.select_dtypes(exclude='object').columns
cat_features = X.select_dtypes(include='object').columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

nuermical_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,cat_features),
        ('StandardScaler',nuermical_transformer,num_features)
    ]
)

X = preprocessor.fit_transform(X)

In [13]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((800, 19), (200, 19))

In [14]:
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true,predicted)
    return mae,mse,rmse,r2_square

In [15]:
models = {
    'Linear Regression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'K-Neighbors Regressor':KNeighborsRegressor(),
    'Decision Tree':DecisionTreeRegressor(),
    'Random Forest Regressor':RandomForestRegressor(),
    'XGBRegressor':XGBRegressor(),
    'CatBoosting Regressor':CatBoostRegressor(verbose=False),
    'AdaBoost Regressor':AdaBoostRegressor()
}

model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae,model_train_mse,model_train_rmse,model_train_r2 = evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_mse,model_test_rmse,model_test_r2 = evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print('MAE:',model_train_mae)
    print('MSE:',model_train_mse)
    print('RMSE:',model_train_rmse)


    print('----------------------------------')

    print('Model Testing Performance')
    print('MAE:',model_test_mae)
    print('MSE:',model_test_mse)
    print('RMSE:',model_test_rmse)
    print('R2 Score:',model_test_r2)

    print('----------------------------------')

Linear Regression
Model Training Performance
MAE: 4.266711846071957
MSE: 28.33487038064859
RMSE: 5.323050852720514
----------------------------------
Model Testing Performance
MAE: 4.21476314247485
MSE: 29.095169866715487
RMSE: 5.393993869732843
R2 Score: 0.8804332983749565
----------------------------------
Lasso
Model Training Performance
MAE: 5.206302661246526
MSE: 43.47840400585579
RMSE: 6.593815587795566
----------------------------------
Model Testing Performance
MAE: 5.157881810347763
MSE: 42.5064168384116
RMSE: 6.519694535667419
R2 Score: 0.8253197323627853
----------------------------------
Ridge
Model Training Performance
MAE: 4.264987823725981
MSE: 28.33778823308244
RMSE: 5.323324922741654
----------------------------------
Model Testing Performance
MAE: 4.2111006880142625
MSE: 29.056272192348324
RMSE: 5.390387016935642
R2 Score: 0.8805931485028737
----------------------------------
K-Neighbors Regressor
Model Training Performance
MAE: 4.516749999999999
MSE: 32.57765
RMSE: 5.707683417990174
----------------------------------
Model Testing Performance
MAE: 5.621
MSE: 52.6066
RMSE: 7.253040741647602
R2 Score: 0.7838129945787431
----------------------------------
Decision Tree
Model Training Performance
MAE: 0.01875
MSE: 0.078125
RMSE: 0.2795084971874737
----------------------------------
Model Testing Performance
MAE: 6.285
MSE: 61.775
RMSE: 7.859707373687649
R2 Score: 0.7461354229336594
----------------------------------
Random Forest Regressor
Model Training Performance
MAE: 1.8248479166666667
MSE: 5.269727008680555
RMSE: 2.295588597436517
----------------------------------
Model Testing Performance
MAE: 4.686062499999999
MSE: 36.361038809027775
RMSE: 6.030011509858649
R2 Score: 0.8505741847196013
----------------------------------
XGBRegressor
Model Training Performance
MAE: 0.687466561794281
MSE: 1.0146163702011108
RMSE: 1.0072816737145132
----------------------------------
Model Testing Performance
MAE: 5.057730674743652
MSE: 41.90370559692383
RMSE: 6.47330716071189
R2 Score: 0.8277965784072876
----------------------------------
CatBoosting Regressor
Model Training Performance
MAE: 2.405393926779502
MSE: 9.257805405523678
RMSE: 3.042664195326799
----------------------------------
Model Testing Performance
MAE: 4.612531714976557
MSE: 36.10365799356841
RMSE: 6.008631956907363
R2 Score: 0.8516318920747058
----------------------------------
AdaBoost Regressor
Model Training Performance
MAE: 4.7795409802851205
MSE: 33.974672740905106
RMSE: 5.828779695691467
----------------------------------
Model Testing Performance
MAE: 4.713436609437992
MSE: 37.28754507792307
RMSE: 6.106352845842031
R2 Score: 0.8467667039894933
----------------------------------